# Generated by Django 4.1.10 on 2023-08-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='user address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=11, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='signature',
            field=models.TextField(blank=True, default='', verbose_name='user signature'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
