#define REDIS_GIT_SHA1 "576885aa"
#define REDIS_GIT_DIRTY "    6519"
#define REDIS_BUILD_ID "sasa-mac.local-1698111045"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
