# Generated by Django 4.1.11 on 2023-10-23 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatDetail',
            new_name='FlyChat',
        ),
    ]
