# Generated by Django 4.1.10 on 2023-10-26 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_chatdetail_flychat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flychat',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
    ]
